version: '3.8'

services:
  db:
    image: postgres:17
    container_name: url_shortener_db
    restart: always
    environment:
      POSTGRES_USER: deneme
      POSTGRES_PASSWORD: 11281117
      POSTGRES_DB: urlshortenerdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
